### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by swapdisk** [Rezney/leapp-vagrant-rhel7#4]
There's no LICENSE file in the repo. Without a license, it could be assumed “all rights reserved” by default, with no permissions granted to anyone. May I suggest using MIT license as that would be the least restrictive for anybody wanting to include all or part of this code in any other project. Let me know your thoughts or I can just push a PR with the LICENSE file if you like. Thanks!

**Comment by Rezney** [comment]
Hello @swapdisk 
thank you for pointing this out. It is actually pretty easy to do from GH UI. One just create a new file and when you name it "LICENSE", it offers you licenses to choose from :)

![license](https://user-images.githubusercontent.com/11775644/203008691-7ffcbd50-8088-471f-b492-19f829c147e2.png)

Feel free to merge the PR.
https://github.com/Rezney/leapp-vagrant-rhel7/pull/5

**Comment by swapdisk** [comment]
Hi @Rezney. Looks good to me, thanks! 

I don't have permission to merge the PR.

**Comment by Rezney** [comment]
> 

Should be granted now.
